apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "{{{ name }}}"
  namespace: "{{{ namespace }}}"
  labels:
    "team": "{{{ namespace }}}"
spec:
  image: {{image}}
  liveness:
    path: "/actuator/health/liveness"
    initialDelay: 10
  readiness:
    path: "/actuator/health/readiness"
    initialDelay: 10
  startup:
    path: "/actuator/health/readiness"
    initialDelay: 20
    failureThreshold: 100
    periodSeconds: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/actuator/prometheus"
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "{{{ ingress }}}"
  accessPolicy:
    outbound:
      external:
        - host: https://pensjon-jit-for-q.intern.nav.no
      rules:
        - application: "{{{ outbound_application }}}"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "{{{ azure_ad_group }}}"
        extra:
          - "NAVident"
      tenant: nav.no
      replyURLs:
        - "{{{ ingress }}}/login/oauth2/code/azuread"
        - "http://localhost:9080/login/oauth2/code/azuread"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  env:
    - name: "REMOTE"
      value: "{{{ remote }}}"
    - name: PENSJON-JIT-FOR-Q_URL
      value: https://pensjon-jit-for-q.intern.nav.no
    - name: PENSJON-JIT-FOR-Q_SCOPE
      value: api://prod-gcp.pensjon-saksbehandling.pensjon-jit-for-q/.default
    - name: "ENVIRONMENT_NAME"
      value: "{{{ environment }}}"
{{#if enable_webproxy}}
    - name: "JDK_JAVA_OPTIONS"
      value: "$(JAVA_PROXY_OPTIONS)"
{{/if}}
{{#if enable_webproxy}}
  webproxy: true
{{/if}}
