apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjon-azuread-app-gateway"
  namespace: "teampensjon"
  labels:
    "team": "teampensjon"
spec:
  image: {{image}}
  liveness:
    path: "/actuator/health/liveness"
    initialDelay: 10
  readiness:
    path: "/actuator/health/readiness"
    initialDelay: 10
  startup:
    path: "/actuator/health/readiness"
    initialDelay: 20
    failureThreshold: 100
    periodSeconds: 1
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/actuator/prometheus"
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "{{{ ingress }}}"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "{{{ azure_ad_group }}}"
      tenant: nav.no
  env:
    - name: "REMOTE"
      value: "{{{ remote }}}"
  webproxy: true
